import { DayBoard, DayKey, Employee } from "./types";

export const WEEKDAYS: { key: DayKey; letter: string }[] = [
  { key: "sun", letter: "א" },
  { key: "mon", letter: "ב" },
  { key: "tue", letter: "ג" },
  { key: "wed", letter: "ד" },
  { key: "thu", letter: "ה" },
];

export const employees: Employee[] = [
  {
    id: "e1",
    name: "איתי סספורטס",
    initials: "אס",
    color: "#CA8A04",
    type: "hourly",
    availableDays: ["sun", "mon", "tue", "wed"],
  },
  {
    id: "e2",
    name: "דניאל גרון",
    initials: "דג",
    color: "#B45309",
    type: "hourly",
    availableDays: ["sun", "mon", "wed", "thu"],
  },
  {
    id: "e3",
    name: "אביאל דבקרוב",
    initials: "אד",
    color: "#0891B2",
    type: "hourly",
    availableDays: ["sun", "tue", "wed", "thu"],
  },
  {
    id: "e4",
    name: "אלעזר סנבטה",
    initials: "אס",
    color: "#9333EA",
    type: "hourly",
    availableDays: ["mon", "tue", "wed", "thu"],
  },
  {
    id: "e5",
    name: "מיכאל סוסי עטייה",
    initials: "מע",
    color: "#DB2777",
    type: "hourly",
    availableDays: ["sun", "mon", "tue", "thu"],
  },
  {
    id: "e6",
    name: "אורי כהן",
    initials: "אכ",
    color: "#0082C8",
    type: "global",
    availableDays: ["sun", "mon", "tue", "wed", "thu"],
  },
  {
    id: "e7",
    name: "נועה לוי",
    initials: "נל",
    color: "#0082C8",
    type: "global",
    availableDays: ["sun", "mon", "tue", "wed", "thu"],
  },
  {
    id: "e8",
    name: "רון אשכנזי",
    initials: "רא",
    color: "#0082C8",
    type: "global",
    availableDays: ["sun", "mon", "tue", "wed", "thu"],
  },
  {
    id: "e9",
    name: "דניאל שרון",
    initials: "דש",
    color: "#EA580C",
    type: "hourly",
    availableDays: ["sun", "mon", "tue", "wed", "thu"],
  },
];

export function createInitialDays(): DayBoard[] {
  return [
    {
      key: "today",
      weekday: "sun",
      label: "ראשון, 02/08/26",
      tasks: [
        {
          id: "t1",
          icon: "mixer",
          title: "מובילי בטון - לידו, אשדוד",
          time: "06:00",
          period: "morning",
          required: 1,
          assignedIds: ["e2"],
          compatibleIds: ["e1", "e2", "e3", "e9"],
        },
        {
          id: "t2",
          icon: "wrench",
          title: "טיפול מערכת - גדל העמק",
          time: "07:00",
          period: "morning",
          required: 1,
          assignedIds: [],
          compatibleIds: ["e1", "e3", "e5", "e6"],
        },
        {
          id: "t5",
          icon: "wrench",
          title: "התקנה - נתניה 1011",
          time: "08:00",
          period: "morning",
          required: 2,
          assignedIds: ["e1"],
          compatibleIds: ["e1", "e5", "e6", "e8"],
        },
        {
          id: "t3",
          icon: "person",
          title: "ביקור שטח - תל אביב 91",
          time: "13:00",
          period: "afternoon",
          required: 1,
          assignedIds: ["e6"],
          compatibleIds: ["e1", "e6", "e7"],
        },
        {
          id: "t9",
          icon: "person",
          title: "ביקור שטח - אם ישראל",
          time: "14:00",
          period: "afternoon",
          required: 1,
          assignedIds: [],
          compatibleIds: ["e6", "e7"],
        },
        {
          id: "t4",
          icon: "wrench",
          title: "תחזוקה - גרנד, חולון",
          time: "18:00",
          period: "evening",
          required: 1,
          assignedIds: [],
          compatibleIds: ["e2", "e4", "e9"],
        },
        {
          id: "t14",
          icon: "wrench",
          title: "תחזוקה - בת שמואל",
          time: "19:00",
          period: "evening",
          required: 1,
          assignedIds: [],
          compatibleIds: ["e4", "e9"],
        },
      ],
    },
    {
      key: "tomorrow",
      weekday: "mon",
      label: "שני, 03/08/26",
      tasks: [
        {
          id: "t6",
          icon: "briefcase",
          title: "שעות עבודה משרדיות",
          time: "07:58",
          period: "morning",
          required: 1,
          assignedIds: ["e7"],
          compatibleIds: ["e6", "e7", "e8"],
        },
        {
          id: "t7",
          icon: "wrench",
          title: "כיסוי תחזוקה - דרום",
          time: "08:00",
          period: "morning",
          required: 1,
          assignedIds: ["e3"],
          compatibleIds: ["e2", "e3", "e9"],
        },
        {
          id: "t8",
          icon: "mixer",
          title: "מובילי בטון - לידו, אשדוד",
          time: "09:00",
          period: "morning",
          required: 1,
          assignedIds: [],
          compatibleIds: ["e1", "e2"],
        },
        {
          id: "t10",
          icon: "wrench",
          title: "התקנה - מזדמן",
          time: "13:00",
          period: "afternoon",
          required: 2,
          assignedIds: ["e1", "e5"],
          compatibleIds: ["e1", "e5", "e9"],
        },
        {
          id: "t12",
          icon: "wrench",
          title: "כיסוי תחזוקה - דרום",
          time: "14:00",
          period: "afternoon",
          required: 4,
          assignedIds: ["e3", "e5"],
          compatibleIds: ["e1", "e3", "e5", "e9"],
        },
        {
          id: "t16",
          icon: "wrench",
          title: "תחזוקה - אור יהודה",
          time: "18:00",
          period: "evening",
          required: 1,
          assignedIds: ["e5"],
          compatibleIds: ["e5", "e6"],
        },
        {
          id: "t18",
          icon: "mixer",
          title: "מובילי בטון - תל אביב 13",
          time: "19:00",
          period: "evening",
          required: 1,
          assignedIds: [],
          compatibleIds: ["e2", "e9"],
        },
      ],
    },
  ];
}

export function isEmployeeAvailable(employee: Employee, weekday: DayKey) {
  if (employee.type === "global") return true;
  return employee.availableDays.includes(weekday);
}
